version: '3.7'

services:
  database:
    container_name: options_database_local
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  backend:
    container_name: options_backend_local
    build:
      context: ./django_apps
      dockerfile: ./docker/Dockerfile.local
    volumes:
      - ./django_apps/:/home/app/backend/
    ports:
      - 8080:8080
    env_file:
      - ./django_apps/local.env
    environment:
      - DJANGO_COLLECT_STATIC=0
    depends_on:
      - database

  frontend:
    container_name: options_frontend_local
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.local
    volumes:
      - ./frontend:/home/app/frontend
      - /home/app/frontend/node_modules
    ports:
      - 3000:3000
    environment:
      - OPTIONS_BACKEND_HOST=backend
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

volumes:
  postgres_data:
