version: '3.7'

services:
  web:
    build:
        context: ./django_apps
        dockerfile: Dockerfile.prod
    image: 813539762970.dkr.ecr.us-east-2.amazonaws.com/options-ec2:web
    restart: always
    command: gunicorn django_apps.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8080
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    image: 813539762970.dkr.ecr.us-east-2.amazonaws.com/options-ec2:nginx
    restart: always
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume: