version: '3.7'

services:
  backend:
    build:
      context: ./django_apps
      dockerfile: Dockerfile.prod
    restart: always
    command: gunicorn django_apps.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - static_volume:/home/app/backend/staticfiles
    expose:
      - 8080
    env_file:
      - ./.env.staging
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/app/backend/staticfiles
      - frontend_volume:/app/build
    ports:
      - 80:80
    depends_on:
      - backend
  fronted:
    # container_name: fronted
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - frontend_volume:/app/build
volumes:
  frontend_volume:
  static_volume:
  postgres_data: