version: '3.7'

services:
  database:
    container_name: options_database_test
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  backend:
    container_name: options_backend_test
    image: 813539762970.dkr.ecr.us-east-2.amazonaws.com/options-ecs-backend:latest
    ports:
      - 8080:8080
    env_file:
      - ./local.env
    environment:
      - DJANGO_COLLECT_STATIC=0
    depends_on:
      - database
